# Site settings
title: Widevine
email: info@widevine.com
description: ''
permalink: pretty
analytics_code: 

collections:
  posts:
    output: true
    permalink: /posts/:title

# Build settings
safe: false
source: src

plugins:
  - jekyll-feed
  - jekyll-sitemap


# feed:
#   title: Client Name
#   description: Description of feed
#   url: primary url
#   path: alternate path

# Meta Settings
facebook:
  title: 'Widevine'
  description: 'Widevine provides multiplatform DRM and video optimization solutions using industry adopted standards including common encryption (CENC) and encrypted media extensions (EME).'
  featured_image: '/assets/img/og-image.jpg'
twitter:
  username: '@Widevine'
  title: 'Widevine'
  description: 'Widevine provides multiplatform DRM and video optimization solutions using industry adopted standards including common encryption (CENC) and encrypted media extensions (EME).'
  featured_image: '/assets/img/twitter-share-280-150.jpg'
  image_alt_text: 'Widevine'


# External Links
cwip_portal_link: 'https://www.widevine.com/training/cwip'
cwip_forum_link: 'https://groups.google.com/g/cwip-discuss'
portal_request_link: 'https://forms.gle/kphdbKPvSYW1YU58A'
cwip_support_link: 'https://support.google.com/widevine/contact/wv_cwipcf'
cwip_registration_link: 'https://forms.gle/ZfScXdgs4aNWuQzk9'
tech_support_link: 'https://support.google.com/widevine/troubleshooter/6027072'
general_questions_link: 'https://support.google.com/widevine/troubleshooter/6027072#ts=14343707'
documentation_link: 'https://developers.google.com/widevine'
documentation_shaka_player_link: 'https://github.com/google/shaka-player#documentation--important-links'
integration_console_link: 'https://partnerdash.google.com/apps/widevineintegrationconsole/home?a=11332155'
login_link: 'https://accounts.google.com/signin/v2/sl/pwd?service=ah&passive=true&continue=https%3A%2F%2Fappengine.google.com%2F_ah%2Fconflogin%3Fcontinue%3Dhttps%3A%2F%2Fcwip-portal.appspot.com%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin'
terms_of_service_link: 'https://policies.google.com/terms'
privacy_policy_link: 'https://policies.google.com/privacy'
